[overlay]
hotkey = "F2"
weapon = "Vandal"
opacity = 0.85
truncate_skins = true

[columns]
skin = true
rr = true
earned_rr = true
peak_rank = true
previous_rank = true
leaderboard = true
headshot_percent = true
winrate = true
kd = true
level = true

[behavior]
auto_show_pregame = true
auto_hide_ingame = true
party_finder = true
discord_rpc = true

[features]
last_played = true
server_id = false
truncate_names = true
truncate_ranks = true
roman_numerals = true

[star]
enabled = true
backend_url = "https://star-client.fly.dev"
